### PR TITLE
Fix compilation problems in ESP32 and FTP upload errors

### PR DESCRIPTION
**Pull request by carrascoacd**
- Fix compilation problems in ESP32
- Fix FTP upload problem
- Improve the library overall speed in each command

@jaka87 new version, I improved the performance of the library :)

### CODE REVIEW

**Comment by jaka87** [comment]
it think you are missing a file in repo. I get an error
```
In file included from /home/jaka87/Arduino/libraries/ArduinoSIM800L/src/Ftp.cpp:28:
/home/jaka87/Arduino/libraries/ArduinoSIM800L/src/Ftp.h:33:10: fatal error: SD.h: No such file or directory
   33 | #include <SD.h>
      |          ^~~~~~
compilation terminated.
```

**Comment by carrascoacd** [comment]
My bad, sorry. I removed the import. I was playing with the SD library and forgot to remove it

**Comment by carrascoacd** [comment]
I disabled the DEBUG mode, if you need to debug it, you can add a `#define DEBUG true` in the first line of your sketch

**Comment by jaka87** [comment]
I also removed the SD script and put the new version on my test station few hours ago. I also define debug the same way as you so there will be no change necessary. Will let you know if anything breaks. 

It is good to see that you are constantly trying to improve the library.

**Comment by jaka87** [comment]
So far so good. I did notice upload speed is significantly faster than before (10-20s faster on average). Nice!

**Pull request merged**
